# Generated by Django 4.0.3 on 2022-04-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotass', '0002_alter_mascota_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='adoptante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fotografia',
            field=models.ImageField(upload_to='mascota'),
        ),
    ]
