# Generated by Django 4.0.3 on 2022-04-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotass', '0003_mascota_adoptante_alter_mascota_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
