# Generated by Django 4.0.3 on 2022-04-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotass', '0004_alter_mascota_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadomascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotass.estadomascota'),
        ),
    ]
