# Generated by Django 4.0.3 on 2022-04-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotass', '0005_estadomascota_alter_mascota_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadomascota',
            options={'verbose_name': 'estadomascota', 'verbose_name_plural': 'estadosmascota'},
        ),
    ]
