# Generated by Django 4.0.3 on 2022-04-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotass', '0006_alter_estadomascota_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadomascota',
            old_name='estado',
            new_name='situacion',
        ),
    ]
