# Generated by Django 4.0.3 on 2022-04-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotass', '0007_rename_estado_estadomascota_situacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='estadomascota',
        ),
    ]
